[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "FhZgkiYVtM2zEucqsGs7bQ4qNcVexC9CSxzWN1GX5cjS"
token-mover = "DWAaszC54Er23JhfPjKGnbQ5aUsjWmohMpA5dnXbebc1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
